CREATE TABLE IF NOT EXISTS `hr_employee_salary_profile_history` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `employee_id` BIGINT NOT NULL COMMENT '员工ID',
  `template_id_before` BIGINT NULL COMMENT '变更前账套ID',
  `template_id_after` BIGINT NULL COMMENT '变更后账套ID',
  `base_salary_before` DECIMAL(12,2) NULL COMMENT '变更前基本工资',
  `base_salary_after` DECIMAL(12,2) NULL COMMENT '变更后基本工资',
  `allowance_before` DECIMAL(12,2) NULL COMMENT '变更前津贴基数',
  `allowance_after` DECIMAL(12,2) NULL COMMENT '变更后津贴基数',
  `performance_base_before` DECIMAL(12,2) NULL COMMENT '变更前绩效基数',
  `performance_base_after` DECIMAL(12,2) NULL COMMENT '变更后绩效基数',
  `social_insurance_base_before` DECIMAL(12,2) NULL COMMENT '变更前社保基数',
  `social_insurance_base_after` DECIMAL(12,2) NULL COMMENT '变更后社保基数',
  `housing_fund_base_before` DECIMAL(12,2) NULL COMMENT '变更前公积金基数',
  `housing_fund_base_after` DECIMAL(12,2) NULL COMMENT '变更后公积金基数',
  `probation_salary_ratio_before` DECIMAL(8,4) NULL COMMENT '变更前试用期薪资比例',
  `probation_salary_ratio_after` DECIMAL(8,4) NULL COMMENT '变更后试用期薪资比例',
  `change_reason` VARCHAR(255) NULL COMMENT '变更原因',
  `create_by` BIGINT NULL COMMENT '创建人',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` BIGINT NULL COMMENT '更新人',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  `version` INT NOT NULL DEFAULT 0 COMMENT '版本号',
  PRIMARY KEY (`id`),
  KEY `idx_salary_profile_history_employee` (`employee_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='员工薪资档案变更历史表';
