-- 员工档案建表
USE `hrms`;

-- hr_employee（员工主档表）
CREATE TABLE `hr_employee` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `employee_no` VARCHAR(32) NOT NULL COMMENT '工号',
  `user_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '关联系统用户ID',
  `dept_id` BIGINT UNSIGNED NOT NULL COMMENT '所属部门ID',
  `post_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '岗位ID',
  `leader_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '直接汇报人员工ID',
  `employee_name` VARCHAR(64) NOT NULL COMMENT '员工姓名',
  `gender` TINYINT DEFAULT NULL COMMENT '性别：1-男 2-女',
  `phone` VARCHAR(20) NOT NULL COMMENT '手机号码',
  `email` VARCHAR(128) DEFAULT NULL COMMENT '邮箱',
  `id_card_no` VARCHAR(255) DEFAULT NULL COMMENT '身份证号（AES-256 GCM 加密存储）',
  `birthday` DATE DEFAULT NULL COMMENT '生日',
  `domicile_address` VARCHAR(255) DEFAULT NULL COMMENT '户籍地址',
  `current_address` VARCHAR(255) DEFAULT NULL COMMENT '现居住地址',
  `job_level` VARCHAR(16) DEFAULT NULL COMMENT '职级',
  `work_location` VARCHAR(128) DEFAULT NULL COMMENT '工作地点',
  `hire_type` TINYINT DEFAULT NULL COMMENT '入职类型：1-全职 2-兼职 3-实习',
  `employment_status` TINYINT NOT NULL COMMENT '在职状态：1-试用中 2-正式 3-待离职 4-已离职',
  `hire_date` DATE NOT NULL COMMENT '入职日期',
  `probation_month` INT DEFAULT 3 COMMENT '试用期（月）',
  `probation_salary_ratio` DECIMAL(5,2) DEFAULT 100.00 COMMENT '试用期薪资比例（%）',
  `contract_type` TINYINT DEFAULT NULL COMMENT '合同类型：1-固定期限 2-无固定期限 3-劳务合同',
  `contract_expire_date` DATE DEFAULT NULL COMMENT '合同到期日',
  `salary_template_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '薪资账套ID',
  `base_salary` DECIMAL(12,2) DEFAULT NULL COMMENT '基本工资',
  `bank_account` VARCHAR(255) DEFAULT NULL COMMENT '银行账号（AES-256 GCM 加密存储）',
  `bank_name` VARCHAR(128) DEFAULT NULL COMMENT '开户行',
  `emergency_contact` VARCHAR(64) DEFAULT NULL COMMENT '紧急联系人',
  `emergency_phone` VARCHAR(20) DEFAULT NULL COMMENT '紧急联系人电话',
  `create_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '更新人',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  `version` INT NOT NULL DEFAULT 0 COMMENT '版本号',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_hr_employee_no` (`employee_no`),
  UNIQUE KEY `uk_hr_employee_phone` (`phone`),
  UNIQUE KEY `uk_hr_employee_user_id` (`user_id`),
  KEY `idx_hr_employee_dept_id` (`dept_id`),
  KEY `idx_hr_employee_post_id` (`post_id`),
  KEY `idx_hr_employee_leader_id` (`leader_id`),
  KEY `idx_hr_employee_employment_status` (`employment_status`),
  KEY `idx_hr_employee_hire_date` (`hire_date`),
  KEY `idx_hr_employee_contract_expire` (`contract_expire_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='员工主档表';

-- hr_employee_contract（员工合同表）
CREATE TABLE `hr_employee_contract` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `employee_id` BIGINT UNSIGNED NOT NULL COMMENT '员工ID',
  `contract_no` VARCHAR(64) DEFAULT NULL COMMENT '合同编号',
  `contract_type` TINYINT NOT NULL COMMENT '合同类型：1-固定期限 2-无固定期限 3-劳务合同',
  `start_date` DATE DEFAULT NULL COMMENT '合同开始日期',
  `end_date` DATE DEFAULT NULL COMMENT '合同结束日期',
  `probation_month` INT DEFAULT NULL COMMENT '试用期（月）',
  `probation_salary_ratio` DECIMAL(5,2) DEFAULT NULL COMMENT '试用期薪资比例（%）',
  `attachment_file_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '附件文件ID',
  `signing_count` INT NOT NULL DEFAULT 1 COMMENT '续签次数',
  `create_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '更新人',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  `version` INT NOT NULL DEFAULT 0 COMMENT '版本号',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_hr_emp_contract_employee_id` (`employee_id`),
  KEY `idx_hr_emp_contract_end_date` (`end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='员工合同表';
