CREATE TABLE IF NOT EXISTS `hr_salary_payslip_view_record` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `payslip_item_id` BIGINT UNSIGNED NOT NULL COMMENT '工资条明细ID，对应hr_salary_batch_item.id',
  `batch_id` BIGINT UNSIGNED NOT NULL COMMENT '薪资批次ID',
  `employee_id` BIGINT UNSIGNED NOT NULL COMMENT '员工ID',
  `salary_month` CHAR(7) NOT NULL COMMENT '薪资月份 yyyy-MM',
  `first_view_time` DATETIME NOT NULL COMMENT '首次查看时间',
  `last_view_time` DATETIME NOT NULL COMMENT '最近查看时间',
  `view_count` INT NOT NULL DEFAULT 1 COMMENT '查看次数',
  `create_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '更新人',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  `version` INT NOT NULL DEFAULT 0 COMMENT '版本号',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_salary_payslip_view_item` (`payslip_item_id`),
  KEY `idx_salary_payslip_view_employee_month` (`employee_id`, `salary_month`),
  KEY `idx_salary_payslip_view_batch` (`batch_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='工资条查看记录表';
